// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DepreciationUIClient is the client API for DepreciationUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepreciationUIClient interface {
	// ListEngineSpecs returns a list of Depreciation Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DepreciationUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type depreciationUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDepreciationUIClient(cc grpc.ClientConnInterface) DepreciationUIClient {
	return &depreciationUIClient{cc}
}

func (c *depreciationUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DepreciationUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DepreciationUI_ServiceDesc.Streams[0], "/v1.DepreciationUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &depreciationUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DepreciationUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type depreciationUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *depreciationUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *depreciationUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DepreciationUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepreciationUIServer is the server API for DepreciationUI service.
// All implementations must embed UnimplementedDepreciationUIServer
// for forward compatibility
type DepreciationUIServer interface {
	// ListEngineSpecs returns a list of Depreciation Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, DepreciationUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDepreciationUIServer()
}

// UnimplementedDepreciationUIServer must be embedded to have forward compatible implementations.
type UnimplementedDepreciationUIServer struct {
}

func (UnimplementedDepreciationUIServer) ListEngineSpecs(*ListEngineSpecsRequest, DepreciationUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedDepreciationUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDepreciationUIServer) mustEmbedUnimplementedDepreciationUIServer() {}

// UnsafeDepreciationUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepreciationUIServer will
// result in compilation errors.
type UnsafeDepreciationUIServer interface {
	mustEmbedUnimplementedDepreciationUIServer()
}

func RegisterDepreciationUIServer(s grpc.ServiceRegistrar, srv DepreciationUIServer) {
	s.RegisterService(&DepreciationUI_ServiceDesc, srv)
}

func _DepreciationUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DepreciationUIServer).ListEngineSpecs(m, &depreciationUIListEngineSpecsServer{stream})
}

type DepreciationUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type depreciationUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *depreciationUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DepreciationUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepreciationUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DepreciationUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepreciationUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepreciationUI_ServiceDesc is the grpc.ServiceDesc for DepreciationUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepreciationUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DepreciationUI",
	HandlerType: (*DepreciationUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DepreciationUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _DepreciationUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "depreciation-ui.proto",
}
